### ISSUE TITLE
Texture intialization of "Texture" stage of ProlificDreamer

### ISSUE THREAD

**Issue by MrTornado24** [threestudio-project/threestudio#198]
How can we reuse the texture from the coarse stage result as the initialization for the texture stage in ProlificDreamer?

**Comment by bennyguo** [comment]
The problem is that I discard the networks when going from the coarse stage to the geometry stage. You can try setting `system.geometry.geometry_only=false` and `system.geometry_convert_inherit_texture=true` for the geometry stage to keep the networks and setting `system.geometry_convert_inherit_texture=true` for the texture stage to use the inherited texture. Let me know if this does not solve the problem.

**Comment by MrTornado24** [comment]
Thanks for your reply! Yeah, the problem is solved.
