### ISSUE TITLE
Export Meshes Broken

### ISSUE THREAD

**Issue by AmanKishore** [threestudio-project/threestudio#52]
Export meshes are really broken :/ 
<img width="524" alt="image" src="https://github.com/threestudio-project/threestudio/assets/10477380/b8e5a5df-376d-46f3-8544-d9f6fb35cb60">

**Comment by thuliu-yt16** [comment]
This is because the default isosurface threshold is auto. It computes the mean value of the geometry field as the threshold, which is logged to your terminal. So if the geometry is incomplete, you could try a lower manually specific threshold with the option `system.geometry.isosurface_threshold`. Otherwise, if there exist many floaters, you could try a higher value.

**Comment by thuliu-yt16** [comment]
Also see #45

**Comment by bennyguo** [comment]
We just updated the code and greatly improve the quality of exported meshes. Please have a try :)

**Comment by claforte** [comment]
No response from @AmanKishore in two weeks... closing this one, to keep the list of open issues tidy.

**Comment by lakpa-tamang9** [comment]
Hi @thuliu-yt16, where do i change this value, system.geometry.isosurface_threshold?

**Comment by thuliu-yt16** [comment]
> Hi @thuliu-yt16, where do i change this value, system.geometry.isosurface_threshold?

Yeah
